# Finally a docker compose file!
version: "3"

services:
  wottor:
    image: ghcr.io/lockness-ko/wottor:cookie
    network_mode: host

  wot:
    image: ghcr.io/lockness-ko/wot:donut
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
