# Finally a docker compose file!
version: "3"

services:
  wottor:
    image: ghcr.io/lockness-ko/wottor:cookie
    ports:
      - "5090:5090"
  wot:
    image: ghcr.io/lockness-ko/wot:cheese
    stdin_open: true # docker run -i
    tty: true        # docker run -t
